application: congreso-11011376
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
    
- url: /css
  static_dir: css
  
- url: /imagenes
  static_dir: imagenes
  
- url: /login
  script: login.application
  
- url: /index
  script: index.application
  
- url: /cursos
  script: cursos.application
  
- url: /conferencias
  script: conferencias.application

- url: .*
  script: main.application


libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: PIL
  version: "1.1.7"
- name: webob
  version: "1.1.1"
